sudo: required
services:
  - docker

before_install:
  - docker build -t vcc-software/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vcc-software/react-test npm run test

after_success:
  - docker build -t vcc-software/multi-client ./client
  - docker build -t vcc-software/multi-nginx ./nginx
  - docker build -t vcc-software/multi-server ./server
  - docker build -t vcc-software/multi-worker ./worker
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  # Take those images and push them to docker hub
  - docker tag local-image:complex_client new-repo:vcc-software/complex_client
  - docker push new-repo:vcc-software/complex_client
  #- docker tag local-image:multi-nginx new-repo:vcc-software/multi-nginx
  #- docker push new-repo:vcc-software/multi-nginx
  #- docker tag local-image:multi-server new-repo:vcc-software/multi-server
  #- docker push new-repo:vcc-software/multi-server
  #- docker tag local-image:vcc-software/multi-worker new-repo:vcc-software/multi-worker
  #- docker push new-repo:vcc-software/multi-worker
